# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=100)),
                ('numberOfMembers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('thoughtText', models.TextField()),
                ('lastUpdateTime', models.DateTimeField()),
                ('md5HashOfText', models.TextField()),
                ('hashTag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=250)),
            ],
        ),
    ]
